spring.application.name=spring-project-14aprel

server.port=8086

spring.datasource.url=jdbc:mysql://localhost:3306/bookshopping_db
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update